import "server-only";
import { createHash } from "node:crypto";
import JSZip from "jszip";
import { supabaseSession } from "./supabase-session-server";
import { supabaseServer } from "./supabase-server";
import { getActiveWorkspace } from "./queries";
import { generateStatementPackId } from "./statement-id";
import { recordStatementAudit } from "./statement-generation";
import {
  getOrRenderStatementArtifact,
  STATEMENT_LINE_COLUMNS,
  STATEMENT_ROW_COLUMNS,
} from "./statement-render";

// Financial Packs: a synchronous ZIP bundle of several already-generated
// statements (master prompt section 32). Packs are a handful of documents,
// so this runs inline - no worker. The pack row is written by the service
// role only after: (1) the caller is a workspace member (getActiveWorkspace
// / RLS), and (2) every requested statement is visible to them (RLS on
// `statements`), belongs to the active workspace, and is status='ready'.

const MIN_ITEMS = 1;
const MAX_ITEMS = 25;
const UUID_RE =
  /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;

export type PackOutcome =
  | { ok: true; id: string; packId: string }
  | { ok: false; error: string };

export async function createStatementPack(input: {
  statementIds: string[];
  title?: string;
}): Promise<PackOutcome> {
  const ids = Array.from(new Set((input.statementIds ?? []).filter(Boolean)));
  if (ids.length < MIN_ITEMS || ids.length > MAX_ITEMS) {
    return {
      ok: false,
      error: `Choose between ${MIN_ITEMS} and ${MAX_ITEMS} statements.`,
    };
  }
  if (!ids.every((id) => UUID_RE.test(id))) {
    return { ok: false, error: "A statement reference was malformed." };
  }
  const title = input.title?.trim().slice(0, 120) || null;

  const session = await supabaseSession();
  const { data: { user } } = await session.auth.getUser();
  if (!user) return { ok: false, error: "You are not signed in." };

  const workspace = await getActiveWorkspace();
  if (!workspace) {
    return { ok: false, error: "We couldn't determine your workspace." };
  }
  if (workspace.role === "viewer") {
    return { ok: false, error: "Viewers can't create packs in this space." };
  }

  // RLS returns only statements the caller may see.
  const { data: rows, error } = await session
    .from("statements")
    .select(STATEMENT_ROW_COLUMNS)
    .in("id", ids);
  if (error) {
    console.error("createStatementPack: lookup failed", error.message);
    return { ok: false, error: "We couldn't read those statements." };
  }
  const byId = new Map((rows ?? []).map((r) => [r.id as string, r]));
  for (const id of ids) {
    const row = byId.get(id);
    if (!row || row.workspace_id !== workspace.id) {
      return { ok: false, error: "One or more statements aren't available." };
    }
    if (row.status !== "ready") {
      return { ok: false, error: "Every statement in a pack must be ready." };
    }
  }

  const admin = supabaseServer();
  const packUuidRow = await admin
    .from("statement_packs")
    .insert({
      pack_id: generateStatementPackId(),
      workspace_id: workspace.id,
      created_by: user.id,
      statement_ids: ids,
      title,
      item_count: ids.length,
      status: "generating",
    })
    .select("id, pack_id")
    .single();

  if (packUuidRow.error || !packUuidRow.data) {
    console.error(
      "createStatementPack: pack insert failed",
      packUuidRow.error?.message,
    );
    return { ok: false, error: "We couldn't start the pack. Try again." };
  }
  const packUuid = packUuidRow.data.id as string;
  const packPublicId = packUuidRow.data.pack_id as string;

  try {
    const zip = new JSZip();
    for (const id of ids) {
      const statement = byId.get(id)!;
      const { data: lineRows } = await admin
        .from("statement_transactions")
        .select(STATEMENT_LINE_COLUMNS)
        .eq("statement_id", id)
        .order("sort_index", { ascending: true });

      const pdf = await getOrRenderStatementArtifact(
        admin,
        statement,
        lineRows ?? [],
        "pdf",
      );
      if (!pdf.ok) {
        throw new Error(`render ${statement.statement_id}: ${pdf.error}`);
      }
      zip.file(`OneLedger-Statement-${statement.statement_id}.pdf`, pdf.bytes);
    }

    const manifest = {
      packId: packPublicId,
      generatedAt: new Date().toISOString(),
      title,
      statements: ids.map((id) => {
        const s = byId.get(id)!;
        return {
          statementId: s.statement_id,
          type: s.statement_type,
          periodStart: s.period_start,
          periodEnd: s.period_end,
        };
      }),
      note:
        "Generated by OneLedger from records available to the account holder. Not an official statement issued by the originating financial provider.",
    };
    zip.file("MANIFEST.json", JSON.stringify(manifest, null, 2));

    const bytes = Buffer.from(
      await zip.generateAsync({
        type: "uint8array",
        compression: "DEFLATE",
        compressionOptions: { level: 6 },
      }),
    );
    const storagePath = `packs/${packUuid}.zip`;

    const { error: uploadError } = await admin.storage
      .from("statement-artifacts")
      .upload(storagePath, bytes, {
        contentType: "application/zip",
        upsert: true,
      });
    if (uploadError) throw new Error(`upload: ${uploadError.message}`);

    const { error: upErr } = await admin.from("statement_packs").update({
      storage_path: storagePath,
      checksum: createHash("sha256").update(bytes).digest("hex"),
      byte_size: bytes.byteLength,
      status: "ready",
      generated_at: new Date().toISOString(),
    }).eq("id", packUuid).eq("status", "generating");
    if (upErr) throw new Error(`finalize: ${upErr.message}`);

    await recordStatementAudit(admin, {
      workspaceId: workspace.id,
      actorUserId: user.id,
      eventType: "statement.downloaded",
      statementUuid: null,
      metadata: { packId: packPublicId, itemCount: ids.length, format: "pack" },
    });

    return { ok: true, id: packUuid, packId: packPublicId };
  } catch (e) {
    console.error("[statement.monitor] pack_failed", { packUuid }, e);
    await admin.from("statement_packs").update({
      status: "failed",
      failure_reason: "The pack could not be built. Try again.",
    }).eq("id", packUuid);
    return { ok: false, error: "The pack could not be built. Try again." };
  }
}

export async function deleteStatementPack(
  packUuid: string,
): Promise<{ ok: boolean; error?: string }> {
  if (!UUID_RE.test(packUuid)) return { ok: false, error: "Invalid pack." };
  const session = await supabaseSession();
  const { data, error } = await session
    .from("statement_packs")
    .delete()
    .eq("id", packUuid)
    .select("id");
  if (error) return { ok: false, error: "Could not delete the pack." };
  if (!data || data.length === 0) {
    return { ok: false, error: "Pack not found." };
  }
  return { ok: true };
}
