import type { Metadata } from "next";
import { headers } from "next/headers";
import { notFound } from "next/navigation";
import { OneLedgerLogo } from "../../../components/brand/OneLedgerLogo";
import { isFinancialStatementsEnabled } from "../../../lib/financial-statements";
import {
  verifyRateLimited,
  verifyStatementToken,
} from "../../../lib/statement-verify";

export const dynamic = "force-dynamic";

export const metadata: Metadata = {
  title: "Verify a OneLedger statement",
  description:
    "Confirm the identity and integrity of a statement generated by OneLedger.",
  robots: { index: false, follow: false },
};

function fmtDate(iso: string): string {
  return new Date(iso).toLocaleDateString("en-GB", {
    day: "numeric",
    month: "long",
    year: "numeric",
    timeZone: "UTC",
  });
}

function Shell({ children }: { children: React.ReactNode }) {
  return (
    <main className="mx-auto flex min-h-screen max-w-lg flex-col gap-6 px-5 py-12">
      <OneLedgerLogo />
      <h1 className="text-xl font-semibold text-text-primary">
        Statement verification
      </h1>
      {children}
      <p className="mt-auto text-xs text-text-muted">
        This page confirms that a document was generated by OneLedger and has
        not changed since. It is not an endorsement by, or an official record
        of, any bank or mobile-money provider.
      </p>
    </main>
  );
}

function Field({ label, value }: { label: string; value: string }) {
  return (
    <div className="flex justify-between gap-4 border-b border-border-subtle py-2 text-sm">
      <span className="text-text-muted">{label}</span>
      <span className="text-right text-text-primary">{value}</span>
    </div>
  );
}

export default async function VerifyStatementPage(
  { params }: PageProps<"/verify/[token]">,
) {
  if (!isFinancialStatementsEnabled()) notFound();

  const h = await headers();
  const ip = (h.get("x-forwarded-for") ?? "").split(",")[0].trim() || "unknown";
  if (verifyRateLimited(ip)) {
    return (
      <Shell>
        <p className="text-sm text-text-secondary">
          Too many requests. Try again in a minute.
        </p>
      </Shell>
    );
  }

  const { token } = await params;
  const result = await verifyStatementToken(token);

  if (result.status === "not_found") {
    return (
      <Shell>
        <p className="rounded-card border border-border-subtle bg-surface p-4 text-sm text-text-secondary">
          No statement matches this link. The link may be mistyped, or the
          statement may have been deleted.
        </p>
      </Shell>
    );
  }

  if (result.status === "revoked") {
    return (
      <Shell>
        <p className="rounded-card border border-attention/30 bg-attention-bg p-4 text-sm text-attention">
          Verification for statement {result.statementId}{" "}
          has been revoked by the account holder. Treat this document as no
          longer verifiable.
        </p>
      </Shell>
    );
  }

  return (
    <Shell>
      <p className="rounded-card border border-money-positive/30 bg-money-positive-bg p-4 text-sm text-money-positive">
        This is a genuine OneLedger-generated statement.
      </p>
      <div className="rounded-card border border-border-subtle bg-surface p-4">
        <Field label="Statement ID" value={result.statementId} />
        <Field
          label="Generated"
          value={result.generatedAt ? fmtDate(result.generatedAt) : "—"}
        />
        <Field
          label="Period"
          value={`${fmtDate(result.periodStart)} – ${
            fmtDate(result.periodEnd)
          }`}
        />
        <Field
          label="Type"
          value={result.statementType === "detailed" ? "Detailed" : "Standard"}
        />
        <Field
          label="Scope"
          value={result.scope === "filtered"
            ? "Filtered"
            : result.scope === "all_accounts"
            ? "Consolidated"
            : "Single account"}
        />
        <Field label="Accounts" value={`${result.accountCount || "—"}`} />
        <Field label="Transactions" value={`${result.transactionCount}`} />
        <Field label="Currency" value={result.currency} />
        <Field
          label="Integrity"
          value={result.integrity === "fingerprinted"
            ? "A document fingerprint is on file"
            : "No document has been downloaded yet"}
        />
      </div>
      <p className="text-xs text-text-muted">
        No transaction details, balances, account numbers or names are shown
        here or stored for public access.
      </p>
    </Shell>
  );
}
