#!/usr/bin/env python3
"""Generate the iOS PWA launch (splash) assets for the OneLedger app-opening screen.

Two outputs, both derived from the ONE approved mark
(web/public/brand/oneledger/app-icons/icon-512.png - navy negative-space "1",
transparent). Nothing here redraws or recolours the mark; it is only scaled
and composited onto white, exactly like app/apple-icon.png already is.

  1. web/public/brand/oneledger/startup/apple-splash-<W>-<H>.png
     Per-device launch images (white field + centred mark). Without these,
     an installed iOS PWA shows a solid BLACK screen for the whole
     cold-start / network wait. Wired up via `appleWebApp.startupImage`
     in web/app/layout.tsx (this script prints the exact array to paste).

  2. web/components/brand/oneledger-mark-data-uri.ts
     A small (240px) PNG of the mark as a base64 data URI, inlined by
     <BrandSplashScreen> so the logo paints WITH the splash - no separate
     network request that, on a slow link, leaves the white screen empty
     for a beat before the icon appears.

Run from the repo root:  python3 scripts/generate-ios-launch-assets.py
Requires Pillow (`pip install Pillow`). Re-run whenever app/icon.png changes.
"""

from __future__ import annotations

import base64
import io
import pathlib

from PIL import Image

REPO = pathlib.Path(__file__).resolve().parent.parent
WEB = REPO / "web"
SRC_MARK = WEB / "public" / "brand" / "oneledger" / "app-icons" / "icon-512.png"
STARTUP_DIR = WEB / "public" / "brand" / "oneledger" / "startup"
DATA_URI_TS = WEB / "components" / "brand" / "oneledger-mark-data-uri.ts"

WHITE = (255, 255, 255, 255)

# Portrait logical size + devicePixelRatio for every iPhone family still in
# meaningful use. iOS only uses a startup image whose media query matches
# EXACTLY, so gaps here mean a black launch screen on that device - keep
# this list current.
DEVICES: list[tuple[int, int, int]] = [
    (320, 568, 2),   # iPhone SE (1st gen) / 5s
    (375, 667, 2),   # iPhone SE (2nd/3rd gen), 6/7/8
    (414, 736, 3),   # iPhone 6+/7+/8+
    (375, 812, 3),   # iPhone X, XS, 11 Pro, 12 mini, 13 mini
    (414, 896, 2),   # iPhone XR, 11
    (414, 896, 3),   # iPhone XS Max, 11 Pro Max
    (390, 844, 3),   # iPhone 12, 12 Pro, 13, 13 Pro, 14
    (428, 926, 3),   # iPhone 12 Pro Max, 13 Pro Max, 14 Plus
    (393, 852, 3),   # iPhone 14 Pro, 15, 15 Pro, 16
    (430, 932, 3),   # iPhone 14 Pro Max, 15 Plus, 15 Pro Max, 16 Plus
    (402, 874, 3),   # iPhone 16 Pro
    (440, 956, 3),   # iPhone 16 Pro Max
]

# Mark width as a fraction of the device's shorter (portrait width) edge -
# restrained, in the same spirit as the in-app splash's clamp(64-112px).
MARK_FRACTION = 0.24


def _load_mark() -> Image.Image:
    if not SRC_MARK.exists():
        raise SystemExit(f"missing source mark: {SRC_MARK}")
    return Image.open(SRC_MARK).convert("RGBA")


def _scaled(mark: Image.Image, width: int) -> Image.Image:
    h = round(width * mark.height / mark.width)
    return mark.resize((width, h), Image.LANCZOS)


def generate_startup_images(mark: Image.Image) -> list[tuple[int, int, int]]:
    STARTUP_DIR.mkdir(parents=True, exist_ok=True)
    written = []
    for css_w, css_h, dpr in DEVICES:
        px_w, px_h = css_w * dpr, css_h * dpr
        canvas = Image.new("RGB", (px_w, px_h), WHITE[:3])
        logo = _scaled(mark, round(px_w * MARK_FRACTION))
        canvas.paste(
            logo,
            ((px_w - logo.width) // 2, (px_h - logo.height) // 2),
            logo,
        )
        out = STARTUP_DIR / f"apple-splash-{px_w}-{px_h}.png"
        canvas.save(out, "PNG", optimize=True)
        written.append((css_w, css_h, dpr))
        print(f"  {out.relative_to(REPO)}  ({px_w}x{px_h})")
    return written


def generate_inline_data_uri(mark: Image.Image) -> None:
    # The in-app splash always sits on a white field and the logo renders
    # at <=112px, so: composite onto white (no alpha needed), scale to a
    # crisp-at-2x 224px, and quantise - the mark is three flat tones, so a
    # small-palette PNG is a few KB instead of tens.
    small = _scaled(mark, 224)
    flat = Image.new("RGB", small.size, WHITE[:3])
    flat.paste(small, (0, 0), small)
    buf = io.BytesIO()
    flat.quantize(colors=32, method=Image.MEDIANCUT).save(
        buf, "PNG", optimize=True
    )
    b64 = base64.b64encode(buf.getvalue()).decode("ascii")
    uri = f"data:image/png;base64,{b64}"
    DATA_URI_TS.write_text(
        "// GENERATED by scripts/generate-ios-launch-assets.py - do not edit by hand.\n"
        "// A 240px PNG of the approved OneLedger mark, inlined so the opening\n"
        "// screen's logo paints with the splash instead of via a separate\n"
        "// request. Re-run the script if app/icon.png changes.\n"
        f"export const ONELEDGER_MARK_DATA_URI =\n  {uri!r};\n".replace("'", '"'),
    )
    print(f"  {DATA_URI_TS.relative_to(REPO)}  ({len(uri) // 1024} KB data URI)")


def print_metadata_snippet(devices: list[tuple[int, int, int]]) -> None:
    print("\nPaste into web/app/layout.tsx  metadata.appleWebApp.startupImage:\n")
    print("    startupImage: [")
    for css_w, css_h, dpr in devices:
        px_w, px_h = css_w * dpr, css_h * dpr
        media = (
            f"(device-width: {css_w}px) and (device-height: {css_h}px) "
            f"and (-webkit-device-pixel-ratio: {dpr}) and (orientation: portrait)"
        )
        print("      {")
        print(f'        url: "/brand/oneledger/startup/apple-splash-{px_w}-{px_h}.png",')
        print(f'        media: "{media}",')
        print("      },")
    print("    ],")


def main() -> None:
    mark = _load_mark()
    print("startup images:")
    devices = generate_startup_images(mark)
    print("inline data URI:")
    generate_inline_data_uri(mark)
    print_metadata_snippet(devices)


if __name__ == "__main__":
    main()
