-- Device pairing v2: consumer one-time pairing handshake.
--
-- Context: today a non-technical user copies a permanent `x-ingest-key`
-- (pfe_...) plus an endpoint URL and JSON body into Apple Shortcuts. This
-- migration adds the backend so a device can instead exchange a short-lived,
-- single-use pairing token for its own scoped `device_credentials` row - a
-- human never sees a permanent key.
--
-- Scope of this migration:
--   * public.pairing_sessions          - short-lived pairing intent
--   * public.connector_pairing_events  - redacted lifecycle audit (no secrets)
--   * public._enroll_ingestion_connection(...) - the shared enrollment body,
--       factored out of create_ingestion_connection_dual_write so the
--       service-role redemption RPC can reuse the exact same legacy+canonical
--       write path with a trusted (not auth.uid()) owner.
--   * public.create_device_pairing_session(...)  - authenticated, MFA-gated
--   * public.consume_device_pairing_session(...) - service-role only
--   * public.expire_stale_pairing_sessions()     - service-role cleanup
--
-- Nothing here changes live ingestion. `ingestion_connections` stays the
-- authoritative auth/routing path (ADR 0007 - no Stage E work). Everything is
-- additive and reversible; the Edge Function that calls these RPCs is itself
-- dark behind an exact-match `DEVICE_PAIRING_V2=enabled` secret.

-- ===========================================================================
-- 1. pairing_sessions
-- ===========================================================================

create table public.pairing_sessions (
  id uuid primary key default gen_random_uuid(),
  owner_user_id uuid not null references auth.users (id) on delete cascade,
  home_workspace_id uuid not null references public.workspaces (id) on delete restrict,
  connector_key text not null
    check (connector_key ~ '^[a-z][a-z0-9_]{2,63}$'),
  provider text not null check (length(trim(provider)) > 0),
  -- Optional least-privilege route intent. Resolved and re-validated at
  -- redemption; never trusted from the device.
  intended_account_id uuid references public.accounts (id) on delete restrict,
  -- Null  => redemption enrolls a brand new installation (+ legacy row).
  -- Set   => redemption issues an additional credential for this existing
  --          installation (device replacement / second device).
  connector_installation_id uuid
    references public.connector_installations (id) on delete restrict,
  label text not null check (length(trim(label)) > 0),
  -- Reveal-once: only the SHA-256 hash of the pairing token is stored. The
  -- plaintext token is generated by the web app, shown once, never persisted.
  token_hash text not null unique check (token_hash ~ '^[0-9a-f]{64}$'),
  -- Human-visible fragment of the pairing code, safe to render in the UI.
  token_prefix text not null check (token_prefix ~ '^olp_[A-Za-z0-9]{4}$'),
  status text not null default 'pending'
    check (status in ('pending', 'consumed', 'expired', 'cancelled')),
  expires_at timestamptz not null,
  consumed_at timestamptz,
  consumed_device_credential_id uuid references public.device_credentials (id) on delete set null,
  consumed_installation_id uuid references public.connector_installations (id) on delete set null,
  created_by uuid references auth.users (id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint pairing_sessions_consumed_consistent check (
    (status = 'consumed')
      = (consumed_at is not null and consumed_device_credential_id is not null)
  ),
  constraint pairing_sessions_installation_owner_fk
    foreign key (connector_installation_id, owner_user_id)
    references public.connector_installations (id, owner_user_id)
    on delete restrict
);

comment on table public.pairing_sessions is
  'Short-lived (minutes), single-use device pairing intent. A device redeems the token for a scoped device_credentials row. Reveal-once: only token_hash is stored.';
comment on column public.pairing_sessions.connector_installation_id is
  'Null => redemption enrolls a new installation. Set => redemption adds a credential to this existing installation.';
comment on column public.pairing_sessions.token_hash is
  'SHA-256 of the pairing token. Never granted to authenticated; service-role redemption only.';

-- token_hash already has a unique index from its column constraint.
create index idx_pairing_sessions_owner_status
  on public.pairing_sessions (owner_user_id, status);
create index idx_pairing_sessions_pending_expiry
  on public.pairing_sessions (expires_at)
  where status = 'pending';

create trigger set_pairing_sessions_updated_at
  before update on public.pairing_sessions
  for each row execute function public.set_updated_at();

alter table public.pairing_sessions enable row level security;

create policy pairing_sessions_select_owner
  on public.pairing_sessions for select to authenticated
  using (owner_user_id = auth.uid());

revoke all on public.pairing_sessions from anon, authenticated;
-- token_hash is deliberately excluded from the authenticated column grant.
grant select (
  id, owner_user_id, home_workspace_id, connector_key, provider,
  intended_account_id, connector_installation_id, label, token_prefix,
  status, expires_at, consumed_at,
  consumed_device_credential_id, consumed_installation_id,
  created_by, created_at, updated_at
) on public.pairing_sessions to authenticated;
grant select, insert, update, delete on public.pairing_sessions to service_role;

-- ===========================================================================
-- 2. connector_pairing_events - redacted lifecycle audit
-- ===========================================================================

create table public.connector_pairing_events (
  id uuid primary key default gen_random_uuid(),
  event text not null check (event in (
    'device_pairing_started',
    'device_paired',
    'device_pairing_failed',
    'device_test_succeeded',
    'device_test_failed',
    'capture_rejected'
  )),
  pairing_session_id uuid references public.pairing_sessions (id) on delete set null,
  connector_installation_id uuid references public.connector_installations (id) on delete set null,
  device_credential_id uuid references public.device_credentials (id) on delete set null,
  reason_code text check (reason_code is null or reason_code ~ '^[A-Z][A-Z0-9_]{2,63}$'),
  created_at timestamptz not null default now()
);

comment on table public.connector_pairing_events is
  'Redacted device-pairing lifecycle audit. Never stores tokens, secrets, message bodies, amounts, phone numbers, or workspace payloads - only IDs and a machine reason code.';

create index idx_connector_pairing_events_created_at
  on public.connector_pairing_events (created_at);
create index idx_connector_pairing_events_event_created_at
  on public.connector_pairing_events (event, created_at);

alter table public.connector_pairing_events enable row level security;
-- No authenticated/anon policy: this table is service-role diagnostic only.
revoke all on public.connector_pairing_events from anon, authenticated;
grant select, insert on public.connector_pairing_events to service_role;

-- ===========================================================================
-- 3. Shared enrollment body
-- ===========================================================================
-- Factored out of create_ingestion_connection_dual_write
-- (20261013000000_connector_model_stage_c_dual_write.sql). Same legacy +
-- canonical write path, but the owner is passed in as trusted scope instead
-- of read from auth.uid(), so a service-role redemption can call it. No
-- execute grant to authenticated: only other SECURITY DEFINER functions and
-- service_role call this.

create or replace function public._enroll_ingestion_connection(
  p_owner_user_id uuid,
  p_workspace_id uuid,
  p_account_id uuid,
  p_label text,
  p_provider text,
  p_credential_hash text,
  p_credential_prefix text
)
returns uuid
language plpgsql
security definer
set search_path = public
as $$
declare
  v_connection_id uuid;
  v_financial_source_id uuid;
  v_source_owner uuid;
  v_account_name text;
  v_account_provider text;
  v_account_currency char(3);
begin
  if p_owner_user_id is null then
    raise exception 'Enrollment owner is required.';
  end if;

  -- Lock the account while resolving/creating its source so concurrent
  -- enrollments cannot manufacture two canonical sources for one account.
  select a.financial_source_id, fs.owner_user_id, a.name, a.provider, a.currency
  into v_financial_source_id, v_source_owner, v_account_name,
    v_account_provider, v_account_currency
  from public.accounts a
  left join public.financial_sources fs on fs.id = a.financial_source_id
  where a.id = p_account_id
    and a.workspace_id = p_workspace_id
    and a.is_active
    and a.archived_at is null
  for update of a;

  if not found then
    raise exception 'The selected account is unavailable.';
  end if;

  if v_financial_source_id is null then
    insert into public.financial_sources (
      owner_user_id, provider, source_type, display_name, currency, created_by
    ) values (
      p_owner_user_id,
      v_account_provider,
      case v_account_provider
        when 'mtn_momo' then 'mobile_money'
        when 'airtel_money' then 'mobile_money'
        when 'bank' then 'bank_account'
        else 'import'
      end,
      v_account_name,
      v_account_currency,
      p_owner_user_id
    ) returning id into v_financial_source_id;

    update public.accounts
    set financial_source_id = v_financial_source_id
    where id = p_account_id;

    v_source_owner := p_owner_user_id;
  end if;

  if v_source_owner is distinct from p_owner_user_id then
    raise exception 'The financial source is owned by another user.';
  end if;

  insert into public.ingestion_connections (
    workspace_id, account_id, label, provider,
    credential_hash, credential_prefix, created_by
  ) values (
    p_workspace_id, p_account_id, trim(p_label), p_provider,
    p_credential_hash, p_credential_prefix, p_owner_user_id
  ) returning id into v_connection_id;

  perform public.backfill_legacy_ingestion_connection(v_connection_id);
  return v_connection_id;
end;
$$;

comment on function public._enroll_ingestion_connection(uuid, uuid, uuid, text, text, text, text) is
  'Internal enrollment body: atomically creates the legacy ingestion connection and its canonical installation/source/device mapping for a trusted owner. Not granted to authenticated.';
revoke all on function public._enroll_ingestion_connection(uuid, uuid, uuid, text, text, text, text) from public;
grant execute on function public._enroll_ingestion_connection(uuid, uuid, uuid, text, text, text, text) to service_role;

-- Re-point the existing authenticated wrapper at the shared body. Signature,
-- behaviour, and grants are unchanged; the owner/workspace checks stay here.
create or replace function public.create_ingestion_connection_dual_write(
  p_workspace_id uuid,
  p_account_id uuid,
  p_label text,
  p_provider text,
  p_credential_hash text,
  p_credential_prefix text
)
returns uuid
language plpgsql
security definer
set search_path = public
as $$
begin
  if auth.uid() is null then
    raise exception 'Authentication required.';
  end if;

  if not public.is_workspace_member(p_workspace_id, 'owner') then
    raise exception 'Only a workspace owner can create a connection.';
  end if;

  return public._enroll_ingestion_connection(
    auth.uid(), p_workspace_id, p_account_id, p_label, p_provider,
    p_credential_hash, p_credential_prefix
  );
end;
$$;

comment on function public.create_ingestion_connection_dual_write(uuid, uuid, text, text, text, text) is
  'Authenticated Stage C enrollment: workspace-owner gated wrapper over _enroll_ingestion_connection. Plaintext credentials are never accepted.';
revoke all on function public.create_ingestion_connection_dual_write(uuid, uuid, text, text, text, text) from public;
grant execute on function public.create_ingestion_connection_dual_write(uuid, uuid, text, text, text, text) to authenticated;

-- ===========================================================================
-- 4. create_device_pairing_session - authenticated, MFA-gated
-- ===========================================================================

create or replace function public.create_device_pairing_session(
  p_connector_key text,
  p_provider text,
  p_home_workspace_id uuid,
  p_label text,
  p_token_hash text,
  p_token_prefix text,
  p_intended_account_id uuid default null,
  p_connector_installation_id uuid default null
)
returns uuid
language plpgsql
security definer
set search_path = public
as $$
declare
  v_now timestamptz := clock_timestamp();
  v_session_id uuid;
  v_pending_count integer;
begin
  perform public.require_progressive_mfa();

  if p_connector_key is null or p_connector_key !~ '^[a-z][a-z0-9_]{2,63}$' then
    raise exception 'Connector key is invalid.' using errcode = '22023';
  end if;
  if p_provider is null or length(trim(p_provider)) = 0 then
    raise exception 'Provider is required.' using errcode = '22023';
  end if;
  if p_label is null or length(trim(p_label)) = 0 then
    raise exception 'A device label is required.' using errcode = '22023';
  end if;
  if p_token_hash is null or p_token_hash !~ '^[0-9a-f]{64}$' then
    raise exception 'Token hash must be a lowercase SHA-256 digest.' using errcode = '22023';
  end if;
  if p_token_prefix is null or p_token_prefix !~ '^olp_[A-Za-z0-9]{4}$' then
    raise exception 'Token prefix is invalid.' using errcode = '22023';
  end if;

  if not public.is_workspace_member(p_home_workspace_id, 'owner') then
    raise exception 'Only a workspace owner can pair a device.' using errcode = '42501';
  end if;

  if p_connector_installation_id is not null then
    if not exists (
      select 1 from public.connector_installations ci
      where ci.id = p_connector_installation_id
        and ci.owner_user_id = auth.uid()
        and ci.status <> 'revoked'
    ) then
      raise exception 'The connector installation is unavailable.' using errcode = '22023';
    end if;
  end if;

  if p_intended_account_id is not null then
    if not exists (
      select 1
      from public.accounts a
      join public.financial_sources fs on fs.id = a.financial_source_id
      where a.id = p_intended_account_id
        and a.workspace_id = p_home_workspace_id
        and a.is_active
        and a.archived_at is null
        and fs.owner_user_id = auth.uid()
        and (
          p_connector_installation_id is null
          or fs.connector_installation_id = p_connector_installation_id
        )
    ) then
      raise exception 'The selected account is unavailable.' using errcode = '22023';
    end if;
  end if;

  -- Cap concurrent pending sessions per user; expire the oldest excess so a
  -- retry loop cannot accumulate live tokens.
  update public.pairing_sessions
  set status = 'expired'
  where owner_user_id = auth.uid()
    and status = 'pending'
    and id in (
      select id from public.pairing_sessions
      where owner_user_id = auth.uid() and status = 'pending'
      order by created_at desc
      offset 2
    );

  select count(*) into v_pending_count
  from public.pairing_sessions
  where owner_user_id = auth.uid() and status = 'pending';

  if v_pending_count >= 3 then
    raise exception 'Too many pending pairing sessions.' using errcode = '22023';
  end if;

  insert into public.pairing_sessions (
    owner_user_id, home_workspace_id, connector_key, provider,
    intended_account_id, connector_installation_id, label,
    token_hash, token_prefix, expires_at, created_by
  ) values (
    auth.uid(), p_home_workspace_id, p_connector_key, trim(p_provider),
    p_intended_account_id, p_connector_installation_id, trim(p_label),
    p_token_hash, p_token_prefix, v_now + interval '10 minutes', auth.uid()
  ) returning id into v_session_id;

  insert into public.connector_pairing_events (event, pairing_session_id)
  values ('device_pairing_started', v_session_id);

  return v_session_id;
end;
$$;

comment on function public.create_device_pairing_session(text, text, uuid, text, text, text, uuid, uuid) is
  'Authenticated, MFA-gated. Records a short-lived single-use pairing intent. The plaintext token is generated client-side and never reaches the database.';
revoke all on function public.create_device_pairing_session(text, text, uuid, text, text, text, uuid, uuid) from public;
grant execute on function public.create_device_pairing_session(text, text, uuid, text, text, text, uuid, uuid) to authenticated;

-- ===========================================================================
-- 5. consume_device_pairing_session - service-role only
-- ===========================================================================

create or replace function public.consume_device_pairing_session(
  p_token_hash text,
  p_new_credential_hash text,
  p_new_credential_prefix text,
  p_client_version text,
  p_platform text,
  p_device_label text default null
)
returns table (
  device_credential_id uuid,
  connector_installation_id uuid,
  legacy_ingestion_connection_id uuid
)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_session public.pairing_sessions%rowtype;
  v_now timestamptz := clock_timestamp();
  v_connection_id uuid;
  v_installation_id uuid;
  v_credential_id uuid;
  v_legacy_id uuid;
  v_account_id uuid;
  v_label text;
begin
  -- Failure paths RAISE, which rolls back everything this function did in the
  -- current statement - so this function does not try to persist failure
  -- audit rows. The Edge Function that calls it catches the typed error and
  -- writes the redacted connector_pairing_events row itself. Replay/brute
  -- force is bounded by the 10-minute TTL, single use, 128-bit token entropy,
  -- and the caller's rate limiter.
  if p_token_hash is null or p_token_hash !~ '^[0-9a-f]{64}$' then
    raise exception 'PAIRING_INVALID' using errcode = '22023';
  end if;

  select * into v_session
  from public.pairing_sessions
  where token_hash = p_token_hash
  for update;

  if not found then
    raise exception 'PAIRING_INVALID' using errcode = '22023';
  end if;

  if v_session.status = 'consumed' then
    raise exception 'PAIRING_ALREADY_USED' using errcode = '22023';
  end if;

  if v_session.status in ('expired', 'cancelled') or v_session.expires_at <= v_now then
    if v_session.status = 'pending' then
      update public.pairing_sessions set status = 'expired' where id = v_session.id;
    end if;
    raise exception 'PAIRING_EXPIRED' using errcode = '22023';
  end if;

  if p_new_credential_hash is null or p_new_credential_hash !~ '^[0-9a-f]{64}$'
     or p_new_credential_prefix is null or p_new_credential_prefix !~ '^pfe_[A-Za-z0-9_-]{4}$' then
    raise exception 'PAIRING_BAD_CREDENTIAL' using errcode = '22023';
  end if;

  v_label := coalesce(nullif(trim(coalesce(p_device_label, '')), ''), v_session.label);

  if v_session.connector_installation_id is null then
    -- New installation: reuse the full legacy + canonical enrollment path.
    if v_session.intended_account_id is null then
      raise exception 'PAIRING_NO_ROUTE' using errcode = '22023';
    end if;

    v_connection_id := public._enroll_ingestion_connection(
      v_session.owner_user_id, v_session.home_workspace_id,
      v_session.intended_account_id, v_label, v_session.provider,
      p_new_credential_hash, p_new_credential_prefix
    );

    select ic.connector_installation_id, ic.device_credential_id
    into v_installation_id, v_credential_id
    from public.ingestion_connections ic
    where ic.id = v_connection_id;

    v_legacy_id := v_connection_id;
  else
    -- Existing installation: issue an additional scoped credential.
    v_installation_id := v_session.connector_installation_id;

    select ci.legacy_ingestion_connection_id
    into v_legacy_id
    from public.connector_installations ci
    where ci.id = v_installation_id
    for update;

    v_account_id := coalesce(
      v_session.intended_account_id,
      (
        select dc.account_id from public.device_credentials dc
        where dc.connector_installation_id = v_installation_id
          and dc.status = 'active'
        order by dc.created_at asc
        limit 1
      )
    );

    insert into public.device_credentials (
      connector_installation_id, account_id, label,
      credential_hash, credential_prefix, status,
      created_by, legacy_ingestion_connection_id
    ) values (
      v_installation_id, v_account_id, v_label,
      p_new_credential_hash, p_new_credential_prefix, 'active',
      v_session.owner_user_id, v_legacy_id
    ) returning id into v_credential_id;
  end if;

  update public.pairing_sessions
  set status = 'consumed',
      consumed_at = v_now,
      consumed_device_credential_id = v_credential_id,
      consumed_installation_id = v_installation_id
  where id = v_session.id;

  insert into public.connector_pairing_events (
    event, pairing_session_id, connector_installation_id, device_credential_id
  ) values (
    'device_paired', v_session.id, v_installation_id, v_credential_id
  );

  device_credential_id := v_credential_id;
  connector_installation_id := v_installation_id;
  legacy_ingestion_connection_id := v_legacy_id;
  return next;
end;
$$;

comment on function public.consume_device_pairing_session(text, text, text, text, text, text) is
  'Service-role only. Redeems a pending pairing token for a scoped device_credentials row, deriving owner/workspace/account scope from the trusted session row. Single-use and TTL-enforced; failure paths raise typed PAIRING_* errors.';
revoke all on function public.consume_device_pairing_session(text, text, text, text, text, text) from public;
grant execute on function public.consume_device_pairing_session(text, text, text, text, text, text) to service_role;

-- ===========================================================================
-- 6. expire_stale_pairing_sessions - service-role cleanup
-- ===========================================================================

create or replace function public.expire_stale_pairing_sessions()
returns integer
language plpgsql
security definer
set search_path = public
as $$
declare
  v_count integer;
begin
  update public.pairing_sessions
  set status = 'expired'
  where status = 'pending'
    and expires_at <= clock_timestamp();
  get diagnostics v_count = row_count;
  return v_count;
end;
$$;

comment on function public.expire_stale_pairing_sessions() is
  'Service-role cleanup: flips expired pending pairing sessions to status=expired. Safe to run on a schedule.';
revoke all on function public.expire_stale_pairing_sessions() from public;
grant execute on function public.expire_stale_pairing_sessions() to service_role;
